name: Frontend CI

on:
  push:
    branches: [main, develop]
    paths:
      - "frontend/**"
  pull_request:
    branches: [main, develop]
    paths:
      - "frontend/**"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install
        working-directory: frontend/mall

      - name: Build
        run: npm run build
        working-directory: frontend/mall
        env:
          CI: false
      - name: Docker Login
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Docker Build & Push
        run: |
          docker build -t jun9579/amigo-mall:latest ./frontend/mall
          docker push jun9579/amigo-mall:latest
